# Generated by Django 2.0.7 on 2020-03-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_document_inference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='inference',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
