# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-05-01 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200330_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ShowSequence',
            field=models.NullBooleanField(default=True),
        ),
    ]
